# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: hccm-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: 'cost-management'
    spec:
      feoConfigEnabled: true
      serviceTiles:
        - id: 'cost-management'
          section: 'subscriptions'
          group: 'openshift'
          title: 'Cost Management'
          href: '/openshift/cost-management'
          description: 'View your data in Cost Management.'
          icon: OpenShiftIcon
      searchEntries:
        - id: 'cost-management'
          title: 'Cost Management'
          href: '/openshift/cost-management'
          description: 'Understand and track costs for your OpenShift clusters and workloads.'
          alt_title:
            - 'Cost Management'
      navigationSegments:
        - segmentId: 'cost-management'
          navItems:
            - id: 'cost-management.nav'
              title: 'Cost Management'
              expandable: true
              routes:
                - id: 'cost-management.overview'
                  title: 'Overview'
                  href: '/openshift/cost-management'
                  product: 'Red Hat Cost Management'
                - id: 'cost-management.systems'
                  title: 'Systems'
                  href: '/openshift/cost-management/systems'
                  permissions:
                    - method: 'featureFlag'
                      args: [ "cost-management.ui.systems", true ]
                - id: 'cost-management.optimizations'
                  title: 'Optimizations'
                  href: '/openshift/cost-management/optimizations'
                - id: 'cost-management.ocp'
                  title: 'OpenShift'
                  href: '/openshift/cost-management/ocp'
                - id: 'cost-management.aws'
                  title: 'Amazon Web Services'
                  href: '/openshift/cost-management/aws'
                - id: 'cost-management.gcp'
                  title: 'Google Cloud Platform'
                  href: '/openshift/cost-management/gcp'
                - id: 'cost-management.azure'
                  title: 'Microsoft Azure'
                  href: '/openshift/cost-management/azure'
                - id: 'cost-management.explorer'
                  title: 'Cost Explorer'
                  href: '/openshift/cost-management/explorer'
                - id: 'cost-management.settings'
                  title: 'Settings'
                  href: '/openshift/cost-management/settings'
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: 'Cost Management'
      deploymentRepo: https://github.com/project-koku/koku-ui
      frontend:
        paths:
          - '/apps/cost-management'
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: '/apps/cost-management/fed-mods.json'
        modules:
          - id: 'cost-management'
            module: './RootApp'
            routes:
              - pathname: '/openshift/cost-management'
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/cost-mgmt-dev-tenant/koku-frontend
