apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/project-koku/koku-ui?rev={{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push"
      && target_branch in ["main", "prod-stable"]

  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: koku-frontend
    appstudio.openshift.io/component: koku-frontend
    pipelines.appstudio.openshift.io/type: build

  namespace: cost-mgmt-dev-tenant
  name: koku-frontend-on-push

spec:
  params:
    - name: git-url
      value: '{{ source_url }}'

    - name: revision
      value: '{{ revision }}'

    - name: output-image
      value: quay.io/redhat-user-workloads/cost-mgmt-dev-tenant/koku-frontend:{{ revision }}

    - name: dockerfile
      value: Dockerfile

    - name: path-context
      value: .

  pipelineRef:
    name: pipeline-build

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'

    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
