FROM registry.access.redhat.com/ubi10/nodejs-22-minimal AS builder
WORKDIR /app

USER 0

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY apps/koku-ui-onprem/package.json ./apps/koku-ui-onprem/
COPY apps/koku-ui-hccm/package.json ./apps/koku-ui-hccm/
COPY apps/koku-ui-ros/package.json ./apps/koku-ui-ros/
COPY libs ./libs

RUN npm ci

COPY apps/koku-ui-onprem ./apps/koku-ui-onprem/
RUN npm run build --workspace=@koku-ui/koku-ui-onprem

COPY apps/koku-ui-hccm ./apps/koku-ui-hccm/
RUN npm run build:onprem --workspace=@koku-ui/koku-ui-hccm

COPY apps/koku-ui-ros ./apps/koku-ui-ros/
RUN npm run build:onprem --workspace=@koku-ui/koku-ui-ros

USER 1001

FROM registry.access.redhat.com/ubi10/nginx-126

COPY --from=builder /app/apps/koku-ui-onprem/dist ./onprem
COPY --from=builder /app/apps/koku-ui-hccm/dist ./costManagement
COPY --from=builder /app/apps/koku-ui-ros/dist ./costManagementRos

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
