const ADD_ACCOUNT = 'ADD_ACCOUNT';
const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
const DELETE_ACCOUNTS = 'DELETES_ACCOUNTS';
const GET_ACCOUNT = 'GET_ACCOUNT';
const GET_ACCOUNTS = 'GET_ACCOUNTS';
const UPDATE_ACCOUNTS = 'UPDATE_ACCOUNTS';
const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
const UPDATE_ACCOUNT_FIELD = 'UPDATE_ACCOUNT_FIELD';
const GET_ACCOUNT_IMAGES = 'GET_ACCOUNT_IMAGES';
const GET_ACCOUNT_IMAGES_INSTANCES = 'GET_ACCOUNT_IMAGES_INSTANCES';
const GET_ACCOUNT_INSTANCES = 'GET_ACCOUNT_INSTANCES';
// ToDo: clean up account constants, ADD_ACCOUNT_WIZARD not used
const ADD_ACCOUNT_WIZARD = 'ADD_ACCOUNT_WIZARD';
const ADD_ACCOUNT_WIZARD_STEP_POLICY = 'ADD_ACCOUNT_WIZARD_STEP_POLICY';
const INVALID_ACCOUNT_WIZARD_STEP_POLICY = 'INVALID_ACCOUNT_WIZARD_STEP_POLICY';
const ADD_ACCOUNT_WIZARD_STEP_ROLE = 'ADD_ACCOUNT_WIZARD_STEP_ROLE';
const INVALID_ACCOUNT_WIZARD_STEP_ROLE = 'INVALID_ACCOUNT_WIZARD_STEP_ROLE';
const ADD_ACCOUNT_WIZARD_STEP_ARN = 'ADD_ACCOUNT_WIZARD_STEP_ARN';
const INVALID_ACCOUNT_WIZARD_STEP_ARN = 'INVALID_ACCOUNT_WIZARD_STEP_ARN';
// ToDo: clean up account constants, poorly named, aim at using ADD_ACCOUNT_WIZARD_ prefix
const ADD_ACCOUNT_SHOW = 'ADD_ACCOUNT_SHOW';
const UPDATE_ACCOUNT_HIDE = 'UPDATE_ACCOUNT_HIDE';

const EDIT_ACCOUNT_SHOW = 'EDIT_ACCOUNT_SHOW';
const EDIT_ACCOUNT_HIDE = 'EDIT_ACCOUNT_HIDE';

export {
  ADD_ACCOUNT,
  DELETE_ACCOUNT,
  DELETE_ACCOUNTS,
  GET_ACCOUNT,
  GET_ACCOUNTS,
  UPDATE_ACCOUNTS,
  UPDATE_ACCOUNT,
  UPDATE_ACCOUNT_FIELD,
  GET_ACCOUNT_IMAGES,
  GET_ACCOUNT_IMAGES_INSTANCES,
  GET_ACCOUNT_INSTANCES,
  ADD_ACCOUNT_WIZARD,
  ADD_ACCOUNT_WIZARD_STEP_POLICY,
  INVALID_ACCOUNT_WIZARD_STEP_POLICY,
  ADD_ACCOUNT_WIZARD_STEP_ROLE,
  INVALID_ACCOUNT_WIZARD_STEP_ROLE,
  ADD_ACCOUNT_WIZARD_STEP_ARN,
  INVALID_ACCOUNT_WIZARD_STEP_ARN,
  ADD_ACCOUNT_SHOW,
  UPDATE_ACCOUNT_HIDE,
  EDIT_ACCOUNT_SHOW,
  EDIT_ACCOUNT_HIDE,
};
