const TOOLBAR_CLEAR_FILTERS = 'TOOLBAR_CLEAR_FILTERS';
const TOOLBAR_ADD_FILTER = 'TOOLBAR_ADD_FILTER';
const TOOLBAR_REMOVE_FILTER = 'TOOLBAR_REMOVE_FILTER';
const TOOLBAR_SET_DATE_TYPE = 'TOOLBAR_SET_DATE_TYPE';
const TOOLBAR_CLEAR_DATE_TYPE = 'TOOLBAR_CLEAR_DATE_TYPE';
const TOOLBAR_SET_FILTER_TYPE = 'TOOLBAR_SET_FILTER_TYPE';
const TOOLBAR_SET_FILTER_VALUE = 'TOOLBAR_SET_FILTER_VALUE';
const TOOLBAR_SET_SORT_TYPE = 'TOOLBAR_SET_SORT_TYPE';
const TOOLBAR_TOGGLE_SORT_ASCENDING = 'TOOLBAR_TOGGLE_SORT_ASCENDING';

export {
  TOOLBAR_ADD_FILTER,
  TOOLBAR_CLEAR_FILTERS,
  TOOLBAR_REMOVE_FILTER,
  TOOLBAR_SET_DATE_TYPE,
  TOOLBAR_CLEAR_DATE_TYPE,
  TOOLBAR_SET_FILTER_TYPE,
  TOOLBAR_SET_FILTER_VALUE,
  TOOLBAR_SET_SORT_TYPE,
  TOOLBAR_TOGGLE_SORT_ASCENDING,
};
